In [3]:
import numpy as np

%precision 3

'%.3f'

Scipyのライブラリのインポート

In [4]:
# 線形代数用のライブラリ
import scipy.linalg as linalg

# 最適化計算（最小値）用の関数
from scipy.optimize import minimize_scalar

行列計算

行列式と逆行列の計算

In [7]:
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])

# 行列式
print('行列式')
print(linalg.det(matrix))

行列式
-4.0


In [8]:
# 逆行列
print('逆行列')
print(linalg.inv(matrix))

逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


値が正しいかどうか確認してみる
もとの行列と逆行列の積は、単位行列のはず

In [9]:
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


固有値と固有ベクトル

In [11]:
# 固有値と固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)

# 固有値と固有ベクトル
print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)

固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[-0.577 -0.578  0.579]
 [-0.577 -0.21  -0.788]
 [-0.577  0.788  0.209]]


ニュートン法

方程式の解を求める

In [12]:
# 関数の定義
def my_function(x):
    return(x**2 + 2*x + 1)

In [13]:
# ニュートン法の読み込み
from scipy.optimize import newton

# 計算実行
print(newton(my_function, 0))

-0.9999999852953906


最小値を求める

In [14]:
print(minimize_scalar(my_function, method='Brent'))

 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 0.0
       x: -1.0000000000000002
     nit: 4
    nfev: 8
