In [1]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

<h1>インデックス参照</h1>

In [2]:
sample_array = np.arange(10)
print(f'sample_array: {sample_array}')

sample_array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
# 元データ
print(sample_array)

# 前から数字を5つ習得して、sample_array_sliceに入れる（スライス）
sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [4]:
# sample_array_sliceの3文字目までは、10で置換
sample_array_slice[0:3] = 10
print(sample_array_slice)

# スライスの変更はオリジナルのリストの要素も変更されている点に注意
print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


<h3>データのコピー</h3>

In [5]:
# copyして別のobjectを作成
sample_array_copy = np.copy(sample_array)
print(sample_array)

sample_array_copy[0:3] = 20
print(sample_array_copy)

# 元のリストの要素は変更できない
print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


<h3>ブールインデックス参照</h3>

In [7]:
# データの準備
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [8]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [9]:
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

<h3>条件制御</h3>

In [10]:
# 条件制御のためのブール配列を作成
cond_data = np.array([True,True,False,False,True])

# 配列x_arrayを作成
x_array = np.array([1, 2, 3, 4, 5])

# 配列y_arrayを作成
y_array = np.array([100, 200, 300, 400, 500])

# 条件制御実施
print(np.where(cond_data, x_array, y_array))

[  1   2 300 400   5]


<h1>Numpyの演算処理</h1>

<h3>重複の削除</h3>

In [11]:
cond_data = np.array([True,True,False,False,True])

# cond_dataを表示
print(cond_data)

# 重複削除
print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


<h3>ユニバーサル関数</h3>

In [12]:
# ユニバーサル関数
sample_data = np.arange(10)
print(f'元データ：{sample_data}')
print(f'すべての要素の平方根：{np.sqrt(sample_data)}')
print(f'すべての要素のネイピア数：{np.exp(sample_data)}')

元データ：[0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根：[0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイピア数：[1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


<h3>最小、最大、平均、合計の計算</h3>

In [13]:
# arangeで 9つの要素を持つ配列を生成
sample_multi_array_data1 = np.arange(9).reshape(3,3)

print(sample_multi_array_data1)

print(f'最小値 : {sample_multi_array_data1.min()}')
print(f'最大値 : {sample_multi_array_data1.max()}')
print(f'平均値 : {sample_multi_array_data1.mean()}')
print(f'合計 : {sample_multi_array_data1.sum()}')

# 行列を指定して合計値を求める
print(f'行の合計 : {sample_multi_array_data1.sum(axis=1)}')
print(f'列の合計 : {sample_multi_array_data1.sum(axis=0)}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値 : 0
最大値 : 8
平均値 : 4.0
合計 : 36
行の合計 : [ 3 12 21]
列の合計 : [ 9 12 15]


<h3>真偽値の判定<h3>

In [14]:
# 真偽値の配列関数
cond_data = np.array([True,True,False,False,True])

print(f'Trueが少なくとも1つあるかどうか : {cond_data.any()}')
print(f'すべてTrueかどうか : {cond_data.all()}')

Trueが少なくとも1つあるかどうか : True
すべてTrueかどうか : False


In [18]:
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)
print(f'5より大きい数字がいくつあるか : {(sample_multi_array_data1 > 5).sum()}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5より大きい数字がいくつあるか : 3


<h3>対角成分の計算</h3>

In [19]:
# 行列計算
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print(f'対角成分 : {np.diag(sample_multi_array_data1)}')
print(f'対角成分の和 : {np.trace(sample_multi_array_data1)}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分 : [0 4 8]
対角成分の和 : 12


<h1>配列操作とブロードキャスト</h1>

<h3>再形成</h3>

In [20]:
# データの準備
sample_array = np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# 再形成
sample_array2 = sample_array.reshape(2,5)
sample_array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

<h3>データの結合</h3>

In [24]:
# データの準備
sample_array3 = np.array([[1,2,3], [4,5,6]])
sample_array4 = np.array([[7,8,9], [10,11,12]])
print(sample_array3)
print(sample_array4)

# 行方向に結合。パラメータの axisに0を指定
np.concatenate([sample_array3, sample_array4], axis=0)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
# vstackを使った行方向結合の方法
np.vstack((sample_array3, sample_array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
# 列方向の結合
np.concatenate([sample_array3, sample_array4], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [28]:
# 列方向結合の他の方法
np.hstack((sample_array3, sample_array4))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

<h3>配列の分割</h3>

In [29]:
# データの用意
sample_array3 = np.array([[1,2,3], [4,5,6]])
sample_array4 = np.array([[7,8,9], [10,11,12]])
sample_array_vstack = np.vstack((sample_array3, sample_array4))

# 作成したsample_array_vstackを表示
sample_array_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
first, second, third = np.split(sample_array_vstack,[1,3])

print(first)
print(second)
print(third)

[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[10 11 12]]


In [31]:
second[0]

array([4, 5, 6])

In [33]:
# データの用意
sample_array5 = np.array([[13,14,15], [16,17,18], [19,20,21]])
sample_array_vstack2 = np.vstack((sample_array3, sample_array4, sample_array5))

# 元データ
print(sample_array_vstack2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [34]:
first, second, third, fourth = np.split(sample_array_vstack2,[2,3,5])
print('・1つ目：\n',first,'\n')
print('・2つ目：\n',second,'\n')
print('・3つ目：\n',third,'\n')
print('・4つ目：\n',fourth,'\n')

・1つ目：
 [[1 2 3]
 [4 5 6]] 

・2つ目：
 [[7 8 9]] 

・3つ目：
 [[10 11 12]
 [13 14 15]] 

・4つ目：
 [[16 17 18]
 [19 20 21]] 



In [35]:
first[0]

array([1, 2, 3])

In [36]:
first[1]

array([4, 5, 6])

<h3>繰り返し処理</h3>

In [37]:
# repeatを使うと、各要素が指定した回数だけ繰り返されて生成される
first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6])

<h3>ブロードキャスト</h3>

In [38]:
# データの準備
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
sample_array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])